name: Update README 
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 3
      - name: PWD
        run: pwd
      - name: Run-Script
        run: |
          chmod +x ./update-version.sh
          ./update-version.sh
